language: go
sudo: true
install: true

go:
    - 1.7.1
    - 1.7.2
    - 1.7.3
env:
    - GOARCH=amd64

install:
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/urfave/cli
    - go get github.com/fujiwara/shapeio
    - go get github.com/golang/groupcache/lru

before_script:
    # make sure we keep path in tact when we sudo
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

script:
    - goimports -d ./
    - go vet ./...
    - sudo -E go test ./...
    - go build
